---
title: "MATH 216 Homework 2 Shiny App"
author: "Trisha Singh"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(babynames)
library(ggplot2movies)
library(ggthemes)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}

inputPanel(
  
  radioButtons("genre", label = "Select movie genre",
              choices = c("Action", "Animation", "Comedy", "Drama", 
                          "Documentary", "Romance", "Short"))
)

renderPlot({
  
  movies_plot <- movies %>% 
    select_("budget", "rating", input$genre) %>% 
    rename_("type" = input$genre) %>% 
    filter(type==1)
    
  
  ggplot(movies_plot, aes(budget, rating)) + 
    geom_point(alpha=0.3, colour = "darkslateblue", size = 2) + 
    geom_smooth(se=F) +
    theme_minimal() +
    scale_x_log10() +
     theme(text = element_text(family="Verdana"), 
           axis.text.x = element_text(angle = 45, hjust = 1, face = "bold"), 
           axis.text.y = element_text(face = "bold"), 
           plot.title = element_text(size=20)) +
  labs(title = "Relationship of Movie IMDB Rating with Budget",
       y = "IMDB Rating", x = "Log10(Budget)")
  
})
```
